Add Admin API to retrieve the status of EventProcessors.
AxonIQ/axonserver-connector-java pull request #138
Opened 2022-01-19 14:59 UTC by saratry

2022-01-19 15:28 UTC, smcvb approved these changes
Looks good to me :+1:

2022-01-28 09:54 UTC, abuijze requested changes
Just some minor changes for consistent terminology

2022-01-28 09:54 UTC, abuijze commented on src/main/java/io/axoniq/axonserver/connector/admin/AdminChannel.java
> +    ResultStream<EventProcessor> eventProcessorsByApplication(String application);
I think we use the word "component" for this in other parts of the connector. Suggest: `ResultStream<EventProcessor> eventProcessorsByComponent(String componentName);`

2022-01-28 09:54 UTC, abuijze commented on src/main/java/io/axoniq/axonserver/connector/admin/impl/AdminChannelImpl.java
> +    private static final Empty EMPTY = Empty.newBuilder().build();
`Empty.getDefaultInstance()` does the same.

2022-01-28 09:54 UTC, abuijze commented on src/main/java/io/axoniq/axonserver/connector/admin/impl/AdminChannelImpl.java
> +        eventProcessorServiceStub.getEventProcessorsByApplication(request, results);
In other parts, we use the word "component". Suggest to rename to "getEventProcessorsByComponent".

2022-02-03 13:32 UTC, abuijze approved these changes

2022-02-03 14:13 UTC, merged